# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[ï—š](bold green)[ï—š](bold yellow)[ï—š](bold red)[ï—š](bold purple)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
success_symbol = "[ğŸ˜‰](bold green)[â¤](bold yellow)[â¤](bold red)[â¤](bold purple)"

error_symbol = "[âŒ](bold red) "
# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = "ğŸš€"
truncation_length = 4
truncation_symbol = ""
format = '[\($symbol $branch\)]($style) '

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_status]
conflicted = "ğŸ³-conflicted"
ahead = "ğŸğŸ’¨-ahead"
behind = "ğŸ˜°-behind"
diverged = "ğŸ˜µ-diverged"
untracked = "ğŸ¤·â€-untracked"
stashed = "ğŸ“¦-stashed"
modified = "ğŸ“-modified"
staged = '[++\($count\) ğŸ‘-staged](green)'
renamed = "ğŸ‘…-renamed"
deleted = "ğŸ—‘-deleted"

[hostname]
ssh_only = false
format =  "ğŸ™‹ on (bold red) "
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "green bold"
style_root = "white bold"
format = "[mohan]($style) "
disabled = false
show_always = true

[directory]
home_symbol = "ğŸ "
read_only = " ï€£ "
style = "bold yellow"
truncation_length = 2
truncation_symbol = "./"
